version: '3.4'

services:
  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1Secure*Password1
    ports:
      - 1433:1433

  portfoliomanager.api.portofolioapi:
    image: ${DOCKER_REGISTRY-}portfoliomanagerapiportofolioapi
    build:
      context: .
      dockerfile: PortfolioManager.API.PortofolioApi/Dockerfile
    depends_on:
      - db
